const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, '..', 'src', 'features', 'game', 'data', 'locales', 'learning', 'en.ts');
let content = fs.readFileSync(filePath, 'utf8');

const newLesson = `    "fe_11": {
        title: "Smart Beta Strategies",
        content: \`
# Smart Beta: The Best of Both Worlds?

"Smart Beta" (or Factor Investing) is a hybrid strategy that sits between passive indexing and active management. It attempts to beat the market not by picking stocks, but by systematically tilting the portfolio toward factors that have historically outperformed, such as Value, Momentum, or Quality. It offers the potential for higher returns with the low costs and transparency of ETFs. It is "rules-based active management."

## Part 1: What Is Beta?

To understand Smart Beta, you must understand Beta.

*   **Alpha**: The return generated by a manager's skill (stock picking, timing). This is hard to find and expensive.
*   **Beta**: The return generated by the market itself (volatility). This is cheap and easy to get (S&P 500).
*   **Market Cap Weighting**: Traditional indexes (S&P 500) are weighted by size. Apple is 7%, Etsy is 0.01%. This is "Beta."
*   **The Flaw**: Cap-weighting means you buy more of a stock as it gets expensive and less as it gets cheap. You are momentum investing by default.
*   **Smart Beta**: Uses alternative weighting schemes to capture specific "factors" (drivers of return) other than size. It tries to fix the flaws of cap-weighting.

## Part 2: The Value Factor

Buying cheap stocks. The oldest factor.

*   **The Theory**: Stocks that are cheap relative to their fundamentals (low P/E, low P/B, low Price/Sales) tend to outperform expensive stocks over the long term.
*   **Why It Works**: Investors overreact to bad news, pushing prices too low. Value investors profit when the price reverts to fair value. It is the "risk premium" for holding distressed companies.
*   **The ETF**: VTV (Vanguard Value), IWD (Russell 1000 Value), AVUV (Small Cap Value).
*   **The Risk**: "Value Traps." Sometimes a stock is cheap because the company is dying (e.g., Blockbuster, Kodak). Value can underperform for decades (like the 2010s, when Growth crushed Value).
*   **Fama-French**: Academics Eugene Fama and Kenneth French proved that Value is one of the primary drivers of stock returns.

## Part 3: The Momentum Factor

Buying winners.

*   **The Theory**: Stocks that have gone up recently tend to keep going up in the near term (3-12 months). "The trend is your friend."
*   **Why It Works**: Behavioral bias. Investors are slow to accept good news (anchoring) and then herd into the stock (FOMO). They also sell winners too early and hold losers too long.
*   **The ETF**: MTUM (iShares Momentum).
*   **The Risk**: Momentum crashes hard. When the trend turns, these stocks fall the fastest. High turnover leads to tax inefficiency. It is a high-volatility strategy.
*   **Rebalancing**: Momentum funds must rebalance frequently to stay in the hottest stocks.

## Part 4: The Quality Factor

Buying good companies.

*   **The Theory**: Profitable, stable companies with low debt, high ROE (Return on Equity), and consistent earnings outperform junk companies.
*   **Why It Works**: Investors underestimate the power of compounding earnings and overestimate the potential of "lottery ticket" junk stocks. They pay too much for risky growth and too little for boring quality.
*   **The ETF**: QUAL (iShares Quality), VIG (Dividend Appreciation - a proxy for quality).
*   **The Risk**: Quality stocks are often expensive. You rarely get them at a discount. In a speculative bubble, Quality lags.
*   **Buffett's Secret**: Research suggests Warren Buffett's returns are largely explained by buying Quality at a Value price.

## Part 5: The Low Volatility Factor

Buying safety.

*   **The Theory**: Boring, stable stocks (Utilities, Staples, Trash collection) deliver market-like returns with less risk.
*   **Why It Works**: The "Low Volatility Anomaly." Investors crave excitement and high-beta stocks, bidding them up. They neglect boring stocks, leaving them with better risk-adjusted returns.
*   **The ETF**: USMV (iShares Min Vol), SPLV (Invesco Low Vol).
*   **The Risk**: Interest rate sensitivity. These "bond proxies" fall when rates rise. Also, if everyone rushes into safety, these stocks can become dangerously overvalued.

## Part 6: The Small Size Factor

Buying small companies.

*   **The Theory**: Small companies outperform large companies over time.
*   **Why It Works**: Small companies have more room to grow and are riskier/less liquid. Investors demand a "risk premium" to hold them.
*   **The ETF**: IJR (S&P SmallCap 600), VBR (Small Cap Value).
*   **The Risk**: Extreme volatility. Small caps can go nowhere for 10 years while large caps soar (like the 2010s). They are more vulnerable to recessions and high interest rates.
*   **Small Cap Value**: The "Holy Grail" of factors. Combining Small Size + Value has historically produced the highest returns of any equity class.

## Part 7: Multi-Factor Strategies

Why pick just one?

*   **The Problem**: Single factors are cyclical. Value works for 5 years, then Momentum works for 5 years. Holding just one is painful when it's out of favor.
*   **The Solution**: Combine them. Value and Momentum are often negatively correlated (when one zigs, the other zags).
*   **Diversification**: A multi-factor fund smooths out the ride. You always have something working.
*   **The ETF**: GSLC (Goldman Sachs ActiveBeta), VFMF (Vanguard Multifactor).
*   **Complexity**: These funds are harder to understand. You don't always know *why* you are up or down. They are "black boxes" to some extent.

## Part 8: The Costs of Smart Beta

There is no free lunch.

*   **Fees**: Smart Beta ETFs are more expensive than plain vanilla indexes.
    *   *S&P 500 (VOO)*: 0.03%
    *   *Momentum (MTUM)*: 0.15%
    *   *Multifactor*: 0.20% - 0.40%
    *   *Avantis/DFA*: 0.25% - 0.40%
*   **Tracking Error**: You will deviate from the market.
    *   *The Behavioral Risk*: If the S&P 500 is up 20% and your Value ETF is up only 5%, will you panic and sell? This "tracking error regret" causes many investors to quit at the bottom.
*   **Capacity**: As billions flow into these strategies, the "edge" might disappear. If everyone buys value stocks, they are no longer cheap.

## Part 9: Factor Timing vs. Buy and Hold

Can you time the factors?

*   **The Temptation**: "Value looks cheap, I'll buy Value now. Momentum looks expensive, I'll sell it."
*   **The Reality**: Factor timing is incredibly difficult, even for professionals. Factors can underperform for 10+ years (like Value from 2010-2020).
*   **The Strategy**: Pick a factor you believe in (e.g., Value) and stick with it through the pain. Or buy a multi-factor fund that rebalances for you.
*   **Diversification**: Holding a mix of factors (Value + Momentum + Quality) is safer than betting the farm on one.

## Part 10: Summary and Implementation

Should you use Smart Beta?

*   **For Beginners**: No. Stick to total market indexing (VTI). It's simple, cheap, and guaranteed to capture the market return. You don't need the complexity.
*   **For Enthusiasts**: A "tilt" can make sense.
    *   *Small Cap Value Tilt*: Adding 10-20% VBR or AVUV to a portfolio is a popular strategy to chase higher long-term returns.
*   **The Golden Rule**: Only choose a factor if you believe in it enough to hold it for 10+ years of underperformance. If you can't stick with it, the extra fee is wasted.
*   **Research**: Read about Fama-French factor models if you want to go deep. It is the academic foundation of modern finance.
*   **Patience**: Factor premiums are lumpy. They show up in bursts after long periods of drought.
\`,
        keyTakeaways: [
            "Smart Beta tilts portfolios toward factors like Value, Momentum, or Quality.",
            "Historically, these factors have outperformed the broad market, but not always.",
            "Requires higher fees and the patience to endure periods of underperformance.",
            "Small-Cap Value is the most popular factor tilt for long-term growth."
        ]
    },`;

const marker = '"fe_10":';
const startIdx = content.indexOf(marker);
if (startIdx === -1) { console.error('fe_10 not found'); process.exit(1); }

let braceCount = 0;
let endIdx = -1;
let inObj = false;
for (let i = startIdx; i < content.length; i++) {
    if (content[i] === '{') { braceCount++; inObj = true; }
    if (content[i] === '}') {
        braceCount--;
        if (inObj && braceCount === 0) { endIdx = i + 1; break; }
    }
}

if (endIdx === -1) { console.error('fe_10 end not found'); process.exit(1); }

let insertPos = endIdx;
while (insertPos < content.length && (content[insertPos] === ',' || content[insertPos] === '\n' || content[insertPos] === '\r' || content[insertPos] === ' ')) {
    insertPos++;
}

const charCount = newLesson.length;
const partCount = (newLesson.match(/## Part \d+/g) || []).length;
console.log('=== fe_11: Smart Beta - VALIDATION ===');
console.log('Chars:', charCount, (charCount >= 8000 && charCount <= 13000) ? '✓' : '✗');
console.log('Parts:', partCount, (partCount >= 5 && partCount <= 10) ? '✓' : '✗');

if (charCount < 8000 || charCount > 13000 || partCount < 5 || partCount > 10) { process.exit(1); }

const before = content.substring(0, endIdx) + ',\n';
const after = content.substring(insertPos);
fs.writeFileSync(filePath, before + newLesson + '\n    ' + after, 'utf8');
console.log('✓ Added fe_11!');
