const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/features/game/data/locales/learning/en.ts');

const newContent = `    "cb_7": {
        title: "NFTs Explained",
        content: \`
# Non-Fungible Tokens: Digital Ownership and Beyond

NFTs—Non-Fungible Tokens—exploded into mainstream consciousness in 2021 when a digital artwork sold for $69 million. But NFTs are more than just expensive JPEGs. They represent a fundamental shift in how we think about digital ownership, provenance, and authenticity. While the hype has cooled, the technology is quietly transforming art, gaming, music, and real-world assets.

## Part 1: What is an NFT?

Understanding the fundamentals.

**Fungible vs. Non-Fungible**:
*   **Fungible**: Interchangeable. One dollar = another dollar. One Bitcoin = another Bitcoin.
*   **Non-Fungible**: Unique. A painting is not the same as another painting. Your house is unique.

**NFT Definition**:
*   A Non-Fungible Token is a unique digital asset recorded on a blockchain.
*   The token contains metadata (name, description, image link, properties).
*   The blockchain provides proof of ownership and provenance.

**What NFTs Are Not**:
*   NFTs are not the image itself (usually). The image is often stored off-chain (IPFS, Arweave).
*   NFTs do not inherently confer copyright. You own the token, not necessarily the art's rights.

**Token Standards**:
*   **ERC-721**: The original Ethereum NFT standard. Each token is unique.
*   **ERC-1155**: Multi-token standard. Can be NFTs or fungible tokens.
*   Other chains have their own standards (Metaplex on Solana).

## Part 2: How NFTs Work

The technical mechanics.

**Minting**:
*   Creating a new NFT on the blockchain.
*   The creator uploads metadata (image, name, description) and calls a smart contract function.
*   The contract assigns a unique token ID and records ownership.

**Ownership and Transfer**:
*   Ownership is recorded on-chain.
*   Transferring ownership is a blockchain transaction: update the owner field from Alice to Bob.
*   Anyone can verify ownership by checking the blockchain.

**Marketplaces**:
*   NFTs are bought and sold on marketplaces.
*   **OpenSea**: Largest, multi-chain.
*   **Blur**: Pro trading features, aggregated listings.
*   **Magic Eden**: Focused on Solana.
*   Marketplaces take a fee (2-5%) on each sale.

**Royalties**:
*   Creators can set royalties (e.g., 5% of every resale goes to the original creator).
*   Enforcement is contentious—some marketplaces have stopped enforcing royalties.

## Part 3: The Art Market Revolution

NFTs and digital art.

**Before NFTs**:
*   Digital art was easily copied. No scarcity.
*   Artists couldn't monetize digital work the way traditional artists could.

**With NFTs**:
*   Digital art can be "owned." The blockchain proves who owns the original.
*   Scarcity can be enforced (1 of 1, limited editions).
*   Artists can earn royalties on secondary sales.

**The $69 Million Sale**:
*   "Everydays: The First 5000 Days" by Beeple sold at Christie's in March 2021.
*   It was a collage of 5,000 digital artworks created over 13 years.
*   The sale legitimized NFTs in the traditional art world.

**Generative Art**:
*   Art generated by algorithms.
*   Projects like Art Blocks host generative art on Ethereum.
*   When you mint, the algorithm generates a unique piece based on random seeds.

## Part 4: NFTs in Gaming and Metaverse

Beyond art.

**In-Game Items**:
*   Traditionally, in-game items are controlled by the game company. You don't really own them.
*   NFT items are owned by the player. You can sell them outside the game.
*   Example: Axie Infinity—players earn and trade Axies (NFT creatures).

**Play-to-Earn (P2E)**:
*   Players earn crypto or NFTs by playing.
*   Controversial: Often devolves into "pay-to-play-to-earn" schemes. Economies collapse when new players stop joining.

**Virtual Land**:
*   Projects like Decentraland and The Sandbox sell virtual land as NFTs.
*   Owners can build on their land and monetize experiences.
*   Highly speculative—most virtual worlds have low activity.

**Interoperability (The Dream)**:
*   The promise: Own a sword NFT in one game, use it in another.
*   Reality: Game developers have little incentive to support items they didn't create.
*   Still mostly a dream.

## Part 5: NFTs Beyond Art and Gaming

Real-world applications.

**Music**:
*   Musicians sell NFTs representing songs, albums, or experiences.
*   Fans can own a piece of music history.
*   Platforms: Sound.xyz, Catalog.

**Tickets and Events**:
*   NFT tickets can prevent scalping (identity-bound).
*   After the event, the NFT becomes a collectible.

**Physical Collectibles**:
*   Physical items with linked NFTs (phygitals).
*   Nike's .SWOOSH, luxury brands issuing digital twins.

**Real Estate and RWA (Real-World Assets)**:
*   Tokenizing real estate as NFTs.
*   Still early and legally complex.

**Identity and Credentials**:
*   Diplomas, certifications, and credentials as NFTs.
*   Soulbound Tokens (SBTs): Non-transferable NFTs representing identity.

## Part 6: Valuing NFTs

What makes an NFT valuable?

**Scarcity**:
*   1 of 1 art is rarer than 10,000 in a collection.
*   Limited editions can command higher prices.

**Provenance**:
*   The history of ownership. An NFT owned by a celebrity is worth more.
*   Blockchain records this permanently.

**Utility**:
*   Access to communities (token-gated Discord servers).
*   Airdrops and future benefits.
*   Gaming utility.

**Cultural Relevance**:
*   Memes, moments in crypto history.
*   CryptoPunks are valuable because they were first.

**The Greater Fool Theory**:
*   Many NFTs are only valuable because someone else might pay more.
*   When the music stops, holders are left with worthless JPEGs.

## Part 7: Risks and Criticisms

The dark side of NFTs.

**Speculation and Volatility**:
*   Most NFT collections have lost 90%+ of their value since the 2021 peak.
*   Illiquidity: You may not be able to sell at any price.

**Wash Trading**:
*   People trade NFTs with themselves to inflate volume and price.
*   Common on incentivized marketplaces.

**Environmental Concerns**:
*   NFTs on Proof of Work blockchains (pre-Merge Ethereum) had high energy costs.
*   Post-Merge Ethereum is 99.95% more efficient.

**Scams and Rug Pulls**:
*   Fake collections impersonating artists.
*   Projects that promise utility and then disappear.

**Copyright Infringement**:
*   People mint NFTs of art they don't own.
*   Blockchain immutability makes it hard to remove infringing content.

## Part 8: How to Participate Safely

Practical tips.

**Due Diligence**:
*   Research the creator or project team.
*   Check social following, past work, and community.
*   Verify contract addresses on official channels.

**Start Small**:
*   Don't spend more than you can afford to lose.
*   Mass NFT drops are often overpriced. Wait for secondary if unsure.

**Security**:
*   Use a hardware wallet for valuable NFTs.
*   Beware of phishing—fake minting sites, malicious links.

**Revoke Approvals**:
*   When you buy/sell on a marketplace, you approve the contract to move your NFTs.
*   Revoke old approvals on Revoke.cash.

**Long-Term Mindset**:
*   The NFT market is cyclical. Most collections won't survive.
*   If you buy, buy what you love, not what you think will "moon."

## Part 9: Summary and Key Takeaways

*   **NFTs are unique digital assets** recorded on a blockchain, proving ownership and provenance.
*   **Art, gaming, music, and collectibles** are the primary use cases today.
*   **Value drivers include scarcity, provenance, utility, and cultural relevance**.
*   **Most NFTs have lost significant value** since the 2021 peak—speculation is extreme.
*   **Risks include scams, illiquidity, and worthless projects**.
*   **Real-world applications** (tickets, credentials, RWA) are emerging but still early.
*   **Security is critical**: use hardware wallets, verify contracts, revoke approvals.
*   **Buy what you love**—don't treat NFTs as get-rich-quick investments.
\`,
        keyTakeaways: [
            "NFTs are unique digital assets proving ownership and provenance on blockchain.",
            "Art, gaming, and collectibles are the primary use cases.",
            "Value is driven by scarcity, provenance, utility, and cultural relevance.",
            "Most NFTs have lost 90%+ value since the 2021 peak—extreme speculation.",
            "Security is critical: use hardware wallets and verify contracts."
        ]
    },`;

let content = fs.readFileSync(filePath, 'utf8');

const cbExists = content.indexOf('"cb_7":');
if (cbExists !== -1) {
    console.log('cb_7 already exists! Replacing...');
    const startPattern = /    "cb_7": \{[\s\S]*?keyTakeaways: \[[\s\S]*?\]\s*\},/;
    content = content.replace(startPattern, newContent);
} else {
    const prevEnd = content.indexOf('"cb_6":');
    if (prevEnd !== -1) {
        const prevKeyTakeaways = content.indexOf('keyTakeaways:', prevEnd);
        const prevEndBracket = content.indexOf('},', prevKeyTakeaways);
        if (prevEndBracket !== -1) {
            const insertPos = prevEndBracket + 2;
            content = content.slice(0, insertPos) + '\n' + newContent + content.slice(insertPos);
        }
    }
}

fs.writeFileSync(filePath, content, 'utf8');
console.log('cb_7 added successfully!');

const contentStart = newContent.indexOf('content: `');
const contentEnd = newContent.lastIndexOf('`');
const textContent = newContent.substring(contentStart + 10, contentEnd);
const parts = (newContent.match(/## Part \d+/g) || []).length;
console.log(`New content: ${textContent.length} characters, ${parts} parts`);
